apiVersion: v1
kind: Service
metadata:
  name: {{ include "lxcfs-admission-webhook.webhookFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lxcfs-admission-webhook.labels" . | nindent 4 }}
    app: {{ include "lxcfs-admission-webhook.webhookFullname" . }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.webhook.port }}
  selector:
    app: {{ include "lxcfs-admission-webhook.webhookFullname" . }}
