name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: make build

    - name: Run Unit Test
      run: make test-coverage

    - name: Upload Coverage Report to CodeCov
      uses: codecov/codecov-action@v5
      with:
        files: build/coverage.out
